# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
    - name: Setup build 
      run: chmod +x ./build.sh
      run: ./build.sh

    - name: Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
      working-directory: ./build
      run: go test .
